version: "3.6"
services:
    organizr:
        container_name: organizrapp
        hostname: organizr
        image: organizr/organizr:latest
        restart: unless-stopped
        ports:
            - 8345:80
        volumes:
            - /var/www/organizr:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Country/Region
