version: '3'
services:
  web:
    container_name: customname
    image: odoo:14.0
    depends_on:
      - dbcustom
    ports:
      - 8936:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=dbcustom
      - USER=clickonodoo
      - PASSWORD=sgg-g40j0f-dkGGW#g-
      - APP_URL=custom
    restart: always
    command: bash -c "cd /usr/lib/python3/dist-packages && pip3 install pandas"
  dbcustom:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=sgg-g40j0f-dkGGW#g-
      - POSTGRES_USER=odoocustom
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
