version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - PASSWORD=psdfjh8024-df2DF6 #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=sg-2466mhgH37-8 #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=clickoncode.onthewifi.com #optional
    volumes:
      - /var/www/vscode:/config
    ports:
      - 8453:8443
    restart: unless-stopped
